Implemented task 1 -- CLI
Denzed/Software-Design-6th-semester pull request #1
Opened 2018-02-28 14:06 UTC by Denzed

2018-03-21 19:54 UTC, yurii-litvinov requested changes
- Такая диаграмма не очень полезна, потому как не отражает связей между классами в разных пакетах. Это, в общем-то, можно не править, если это сложно.
- Половина тестов не прошла под виндой из-за концов строк, хотя про существование винды Вы явно подумали (что приятно).
- Можно добиться интересного эффекта, написав
```
echo "
```
и нажав Enter, затем Ctrl-D

В целом всё очень круто, но поправьте замечания, пожалуйста.

2018-03-21 19:54 UTC, yurii-litvinov commented on src/main/kotlin/ru.spbau.mit/aush/Repl.kt
> +        } catch (throwable: Throwable) {
Ловить Throwable --- плохая идея. Общая идея "может произойти любая неведомая фигня, давайте скажем об этом пользователю и продолжим работу" понятна, но неведомая фигня может включать ошибку кодирования (например, NullPointerException), и в этом случае продолжать работу уже нежелательно. Лучше ловить только свои исключения.

2018-03-21 19:54 UTC, yurii-litvinov commented on src/main/kotlin/ru.spbau.mit/aush/lexer/data.kt
> + *
Гм :)

2018-03-21 19:54 UTC, yurii-litvinov commented on src/test/kotlin/ru/spbau/mit/aush/TestRepl.kt
> +import com.sun.xml.internal.messaging.saaj.util.ByteOutputStream
Я думаю, тут не то имелось в виду

2018-03-22 15:30 UTC, Denzed commented on src/test/kotlin/ru/spbau/mit/aush/TestRepl.kt
> +import com.sun.xml.internal.messaging.saaj.util.ByteOutputStream
Да, просто разрешил идее дополнить по аналогии с `.byteInputStream` (который, как оказалось, внутри создаёт как раз `ByteArray*Stream`)

2018-03-22 15:30 UTC, Denzed commented on src/main/kotlin/ru.spbau.mit/aush/lexer/data.kt
> + *
Начал писать комментарий, а потом решил, что слишком очевидно для комментария. А поле просто забыл удалить)

2018-03-22 15:31 UTC, Denzed commented on src/main/kotlin/ru.spbau.mit/aush/Repl.kt
> +        } catch (throwable: Throwable) {
Поменял на `EvaluationException`

2018-03-22 15:35 UTC, Denzed commented
По поводу истории с `echo "` + `Ctrl+D`: тут сложно с ходу что-то сделать, потому что для InputStream надо как-то узнавать, что он закрыт.

2018-03-25 09:19 UTC, yurii-litvinov approved these changes
Тесты под виндой так и не проходят. По поводу `Ctrl-D` я имел в виду не столько корректную обработку самого `Ctrl-D`, сколько странное поведение `echo "`. Наверное, ожидалась ошибка ещё при нажатии на перевод строки после кавычки.

Но ладно, оставшиеся замечания несущественны, так что зачтена.

2018-03-25 11:04 UTC, Denzed commented
В реализации этого поведения я ориентировался на Bash, который ждёт дополнительного ввода, который закрыл бы кавычку.

2018-03-25 11:05 UTC, closed without merging