Implemented simplified grep command
Denzed/Software-Design-6th-semester pull request #2
Opened 2018-03-20 08:17 UTC by Denzed

2018-04-21 13:38 UTC, yurii-litvinov requested changes
Как-то странно работает -w:
```
> grep -w maven build.gradle
> grep maven build.gradle
build.gradle:        mavenCentral()
build.gradle:    mavenCentral()
build.gradle:    maven {
build.gradle:        url "https://dl.bintray.com/xenomachina/maven"
```
По крайней мере, третье вхождение должно было найтись с -w.

В остальном всё ок, но всё-таки поправьте, пожалуйста.

2018-04-21 13:38 UTC, yurii-litvinov commented on README.md
> +# HW02 AUsh::grep
Старое содержимое этого файла лучше оставить, ведь пуллреквест должно быть можно вмерджить. Лучше дописать к уже существующему.

2018-04-22 17:45 UTC, Denzed commented
Кажется, регулярка портилась на этапе составления из за escaping-а. Теперь должно работать. Помимо прочего, добавил соответствующий тест.

2018-04-24 08:08 UTC, yurii-litvinov approved these changes
Да, теперь всё ок, зачтена.

2018-05-01 18:51 UTC, merged